apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: flask-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
