apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sma1kyyy/DevOps.git
    targetRevision: master
    path: k3s/charts/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
