apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
  namespace: flask-stack
type: Opaque
stringData:
  DATABASE_URL: postgresql://flask:flask@postgres:5432/tasks
  REDIS_URL: redis://redis:6379/0
