# # этот плейбук автоматизирует подготовку второй виртуальной машины под физическую репликацию
- name: prepare replica postgresql host
  hosts: replica
  become: true
  vars:
    # здесь перечислены пакеты для postgresql 16 на replica
    postgres_packages:
      - postgresql-16
      - postgresql-client-16
      - postgresql-contrib-16
      - python3-psycopg2

  tasks:
    # обновляем индекс пакетов
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true
      ignore_errors: yes

    # устанавливаем postgresql 16
    - name: install postgresql packages
      ansible.builtin.apt:
        name: "{{ postgres_packages }}"
        state: present

    # создаем каталог /pg_data
    - name: create pg_data directory
      ansible.builtin.file:
        path: /pg_data
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    # останавливаем стандартный сервис до ручных действий
    - name: stop postgresql service
      ansible.builtin.systemd:
        name: postgresql
        state: stopped
        enabled: true

    # удаляем стандартный кластер если пакет его уже создал
    - name: drop default cluster if exists
      ansible.builtin.command:
        cmd: pg_dropcluster --stop 16 main
      register: drop_cluster
      changed_when: drop_cluster.rc == 0
      failed_when: drop_cluster.rc not in [0, 1]