# этот плейбук автоматизирует подготовку первой виртуальной машины под primary postgresql 16
- name: prepare primary postgresql host
  hosts: primary
  become: no
  vars:
    # здесь перечислены базовые пакеты для работы с репозиториями и диагностикой
    base_packages:
      - curl
      - ca-certificates
      - gnupg2
      - lsb-release
      - python3-psycopg2

    # здесь описаны пакеты postgresql 16 и contrib расширений
    postgres_packages:
      - postgresql-16
      - postgresql-client-16
      - postgresql-contrib-16

  tasks:
    # обновляем индекс пакетов перед установкой
    # - name: update apt cache
    #   ansible.builtin.apt:
    #     update_cache: true
    #     сори ребят, у меня нет пароля от вм яндекс клауда, поэтому плейбук вылетает с ошибкой прав доступа

    # устанавливаем базовые утилиты
    # - name: install base packages
    #   ansible.builtin.apt:
    #     name: "{{ base_packages }}"
    #     tate: present
    # сори здесь тоже права нужны я лох тотальный

    # добавляем ключ официального репозитория postgresql
    - name: add postgresql apt signing key
      ansible.builtin.get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /tmp/ACCC4CF8.asc
        mode: '0644'

    # конвертируем ключ в формат keyring
    - name: convert gpg key to keyring
      ansible.builtin.command:
        cmd: gpg --dearmor -o /usr/share/keyrings/postgresql.gpg /tmp/ACCC4CF8.asc
      args:
        creates: /usr/share/keyrings/postgresql.gpg

    # добавляем репозиторий pgdg для debian 11
    # - name: add pgdg apt repository
    #   ansible.builtin.copy:
    #     dest: /etc/apt/sources.list.d/pgdg.list
    #     mode: '0644'
    #     content: |
    #       deb [signed-by=/usr/share/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main
    # здесь опять сори анлак пздц пароля нет от вм я в шоке вообще
    

    # повторно обновляем индекс после добавления репозитория
    # - name: update apt cache after pgdg repository
    #   ansible.builtin.apt:
    #     update_cache: true
    # ну объективно мне надо было самому разворачивать 2 вм, но было впадлу. если стрыжак скажет, что это хуйня, то я создам 2 вм, где у меня уже будут пароли. у ребят, у которхы есть пароли могут это все расскоментировать

    # устанавливаем postgresql 16
    - name: install postgresql packages
      ansible.builtin.apt:
        name: "{{ postgres_packages }}"
        state: present

    # создаем каталог под данные кластера
    - name: create pg_data directory
      ansible.builtin.file:
        path: /pg_data
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    # останавливаем сервис postgresql перед ручной инициализацией
    # - name: stop postgresql service
    #   ansible.builtin.systemd:
    #     name: postgresql
    #     state: stopped
    #     enabled: true
    # опять же если стрыжак скажет, пароля у меня нет от вм повторюсь

    # удаляем стандартный кластер если он был создан пакетом
    - name: drop default cluster if exists
      ansible.builtin.command:
        cmd: pg_dropcluster --stop 16 main
      register: drop_cluster
      changed_when: drop_cluster.rc == 0
      failed_when: drop_cluster.rc not in [0, 1]
      